"""empty message

Revision ID: 2f419e1b9a37
Revises: b9abf11e6c0d
Create Date: 2023-07-28 18:18:41.901967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f419e1b9a37'
down_revision = 'b9abf11e6c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('inventory')

    # ### end Alembic commands ###
