"""empty message

Revision ID: 4298464af6b8
Revises: 3a0513a00a42
Create Date: 2023-07-26 19:08:54.524082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4298464af6b8'
down_revision = '3a0513a00a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_address_details', sa.String(length=255), nullable=False),
    sa.Column('main_address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_address_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_address_id'))

    op.drop_table('sub_address')
    # ### end Alembic commands ###
