"""empty message

Revision ID: 68c30a87e313
Revises: bfa7dd4c6ac2
Create Date: 2023-07-26 21:08:32.346417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c30a87e313'
down_revision = 'bfa7dd4c6ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'object', ['object_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('object_id')

    # ### end Alembic commands ###
