"""empty message

Revision ID: bfa7dd4c6ac2
Revises: 0555b0756416
Create Date: 2023-07-26 20:44:20.019183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfa7dd4c6ac2'
down_revision = '0555b0756416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_ibfk_2', type_='foreignkey')
        batch_op.drop_column('orderitem_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderitem_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('order_ibfk_2', 'orderitem', ['orderitem_id'], ['id'])

    # ### end Alembic commands ###
